services:
  - type: web
    name: alexanda-martinz-ai
    runtime: docker
    plan: starter
    region: oregon
    env:
      NODE_ENV: production
    dockerfile: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
    autoDeploy: true
